[project]
name = "saev"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beartype>=0.19.0",
    "datasets>=3.0.1",
    "einops>=0.8.0",
    "jaxtyping>=0.2.34",
    "marimo>=0.9.10",
    "pillow>=11.0.0",
    "torch>=2.5.0",
    "tqdm>=4.66.5",
    "transformers>=4.45.2",
    "tyro>=0.8.12",
    "wandb>=0.18.5",
]

[tool.ruff.lint]
ignore = ["F722"]
