tag = "classification-v1.0"

lr = [1e-4, 3e-4, 1e-3, 3e-3]

n_lr_warmup = 500
n_sparsity_warmup = 500

[sae]
sparsity_coeff = [4e-4, 8e-4, 1.6e-3]
ghost_grads = false
normalize_w_dec = true
remove_parallel_grads = true
exp_factor = [16, 32]

[data]
scale_mean = true
scale_norm = true
