sparsity_coeff = [1e-5, 3e-4, 1e-4, 3e-4, 1e-3]
lr = [5e-5, 1e-4, 2e-4, 4e-4]

# Disable re-init
n_reinit_batches = 0

# No warmup
n_lr_warmup = 0
n_sparsity_coeff_warmup = 0

ghost_grads = false
remove_parallel_grads = false
normalize_w_dec = false


tag = "dumbest"
